services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/apps/api/main
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - NODE_ENV=production
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/apps/worker/main
    env_file: .env
    environment:
      - NODE_ENV=production
    restart: always

  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: npx prisma@5.22.0 migrate deploy
    env_file: .env
    restart: "no"
